version: '3.8'
services:
  app:
    build: .
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 80 --log-level info
    ports:
      - "80:80"
    environment:
      - CONFIGMAP_VARIABLE=${CONFIGMAP_VARIABLE}
      - SECRETS_VARIABLE=${SECRETS_VARIABLE}
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/test_db
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongodb:27017/
      - MONGO_DB=test_db
    depends_on:
      - redis
      - postgres
      - mongodb
      - celery_worker

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  celery_worker:
    build: .
    command: celery -A app.tasks.celery_config worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/test_db
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongodb:27017/
    depends_on:
      - redis
      - postgres
      - mongodb
