version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - CONFIGMAP_VARIABLE=${CONFIGMAP_VARIABLE}
      - SECRETS_VARIABLE=${SECRETS_VARIABLE}
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/test_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db

