version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.0
  deploy-orb: tkuchh/deploy-orb@0.0.4

jobs:
  build-and-test:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - deploy-orb/connect_to_container_repo
      - run:
          name: Build Docker Image
          command: |
            docker build -t gcr.io/testing-234907/template:$CIRCLE_SHA1 -t gcr.io/testing-234907/template:$CIRCLE_BUILD_NUM -t gcr.io/testing-234907/template:latest .
      - run:
          name: Export Environment Variables
          command: |
            env > env_vars
            echo "CONFIGMAP_VARIABLE=success" >> env_vars
            echo "SECRETS_VARIABLE=success" >> env_vars
      - run:
          name: Run Tests in Docker Image
          command: |
            docker run --env-file env_vars gcr.io/testing-234907/template:$CIRCLE_SHA1 pytest /code/tests/
      - run:
          name: Push Docker Image to Container Registry
          command: |
            docker push gcr.io/testing-234907/template:$CIRCLE_SHA1
            docker push gcr.io/testing-234907/template:$CIRCLE_BUILD_NUM
            docker push gcr.io/testing-234907/template:latest


  deploy-dev:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: testing-234907
          cluster_name: dev-cluster
      - deploy-orb/deploy:
          config_path: services/template/development
          kubectl_filename: deployment.yaml
          image_name: template
          image_tag: $CIRCLE_SHA1

  deploy-prod-canary:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: testing-234907
          cluster_name: prod-cluster
      - deploy-orb/deploy:
          config_path: services/template/production
          kubectl_filename: deployment-canary.yaml
          image_name: template
          image_tag: $CIRCLE_SHA1

  rollback-prod-canary:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: testing-234907
          cluster_name: prod-cluster
      - deploy-orb/deploy:
          config_path: services/template/production
          kubectl_filename: deployment-canary.yaml
          image_name: template
          image_tag: $CIRCLE_SHA1


  deploy-prod:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: testing-234907
          cluster_name: prod-cluster
      - deploy-orb/deploy:
          config_path: services/template/production
          kubectl_filename: deployment.yaml
          image_name: template
          image_tag: $CIRCLE_SHA1

  rollback-prod:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: testing-234907
          cluster_name: prod-cluster
      - deploy-orb/deploy:
          config_path: services/template/production
          kubectl_filename: deployment.yaml
          image_name: template
          image_tag: $CIRCLE_SHA1

workflows:
  version: 2
  build-test-release:
    jobs:
      - build-and-test:
          context: gcp_credentials
          filters:
            branches:
              only: main
      - deploy-dev:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - build-and-test
          filters:
            branches:
              only: main
      - confirm-deploy-prod-canary:
          type: approval
          requires:
            - deploy-dev
      - deploy-prod-canary:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - confirm-deploy-prod-canary
          filters:
            branches:
              only: main
      - confirm-deploy-to-prod:
          type: approval
          requires:
            - deploy-prod-canary
      - confirm-rollback-canary:
          type: approval
          requires:
            - deploy-prod-canary

      - rollback-prod-canary:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - confirm-rollback-canary
          filters:
            branches:
              only: main

      - deploy-prod:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - confirm-deploy-to-prod
          filters:
            branches:
              only: main


      - confirm-rollback-prod:
          type: approval
          requires:
            - deploy-prod


      - rollback-prod:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - confirm-rollback-prod
          filters:
            branches:
              only: main