version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.0
  deploy-orb: tkuchh/deploy-orb@0.1.1


jobs:
  build-and-test:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Export Environment Variables
          command: |
            env > env_vars
            echo "CONFIGMAP_VARIABLE=success" >> env_vars
            echo "SECRETS_VARIABLE=success" >> env_vars
      - deploy-orb/build:
          dockerfile_path: .
          image_name: template
          test_runner_env_file: ./env_vars
          test_runner_command: pytest tests --junitxml=/test-results/junit.xml

  deploy-dev:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: dev-cluster

      - deploy-orb/deploy:
          config_path: services/template/development/kubectl
          config_file: deployment.yaml
          image_name: template
          namespace: template
          image_tag: $CIRCLE_SHA1
          deployment_name: template

      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: vpc-test-cluster

      - deploy-orb/deploy:
          config_path: services/template/development/kubectl
          config_file: deployment.yaml
          image_name: template
          namespace: template
          image_tag: $CIRCLE_SHA1
          deployment_name: template

  full-deployment:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: prod-cluster
      - deploy-orb/deploy:
          config_path: services/template/production/kubectl
          config_file: deployment.yaml
          image_name: template
          image_tag: $CIRCLE_SHA1
          namespace: template
          deployment_name: template

workflows:
  version: 2
  build-test-release:
    jobs:
      - build-and-test:
          context: gcp_credentials
          filters:
            branches:
              only: main

      - deploy-dev:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - build-and-test
          filters:
            branches:
              only: main

      #      - confirm-full-deployment:
      #          type: approval
      #          requires:
      #            - deploy-dev

      - full-deployment:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - deploy-dev
          filters:
            branches:
              only: main
