version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.0

commands:
  connect_to_kubernetes:
    parameters:
      project_id:
        type: string
      region:
        default: asia-southeast1
        type: string
      cluster_name:
        type: string
    steps:
      - run:
          name: Authenticate with GCP
          command: echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > ${HOME}/gcp-key.json
      - run:
          name: Set up gcloud and kubectl
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
            gcloud config set project <<parameters.project_id>>
            gcloud container clusters get-credentials <<parameters.cluster_name>> --region <<parameters.region>>
  deploy:
    parameters:
      kubectl_filename:
        type: string
      config_path:
        type: string
    steps:
      - run:
          name: Set up git
          command: |
            cd ~/build
            git config user.email "cicdrunner@template.com"
            git config user.name "CI/CD"
      - run:
          name: Fetch and update latest build config
          command: |
            git clone https://workflowr:$GITHUB_PAT@github.com/tkuchh/build.git ~/build
            cd ~/build/<<parameters.config_path>>
            sed -i "s|image:\(.*\)/template:.*|image:\1/template:$CIRCLE_SHA1|" ./<<parameters.kubectl_filename>>
      - run:
          name: Deploy to GKE
          command: kubectl apply -f ~/build/<<parameters.config_path>>/<<parameters.kubectl_filename>>
      - run:
          name: Push the new version to git
          command: |
            git add ./<<parameters.config_path>>
            git commit -m "Update image tag to new-tag"
            git push origin main


jobs:
  build-and-test:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate with GCP
          command: echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > ${HOME}/gcp-key.json
      - run:
          name: Configure Docker for GCR
          command: |
            cat ${HOME}/gcp-key.json | docker login -u _json_key --password-stdin https://gcr.io
      - run:
          name: Build Docker Image
          command: |
            docker build -t gcr.io/testing-234907/template:$CIRCLE_SHA1 -t gcr.io/testing-234907/template:latest .
      - run:
          name: Export Environment Variables
          command: |
            env > env_vars
            echo "CONFIGMAP_VARIABLE=success" >> env_vars
            echo "SECRETS_VARIABLE=success" >> env_vars
      - run:
          name: Run Tests in Docker Image
          command: |
            docker run --env-file env_vars gcr.io/testing-234907/template:$CIRCLE_SHA1 pytest /code/tests/
      - run:
          name: Push Docker Image to Container Registry
          command: |
            docker push gcr.io/testing-234907/template:$CIRCLE_SHA1
            docker push gcr.io/testing-234907/template:latest

  deploy-dev:
    docker:
      - image: google/cloud-sdk
    steps:
      - connect_to_kubernetes:
          project_id: testing-234907
          cluster_name: dev-cluster
      - deploy:
          config_path: services/template/development
          kubectl_filename: deployment.yaml

  deploy-prod-canary:
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker
      - run:
          name: Authenticate with GCP
          command: echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > ${HOME}/gcp-key.json
      - run:
          name: Set up gcloud and kubectl
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
            gcloud config set project testing-234907
            gcloud container clusters get-credentials prod-cluster --region asia-southeast1
      - run:
          name: Fetch and update latest build config
          command: |
            git clone https://workflowr:$GITHUB_PAT@github.com/tkuchh/build.git ~/build
            cd ~/build/services/template/production
            sed -i "s|image:\(.*\)/template:.*|image:\1/template:$CIRCLE_SHA1|" ./deployment-canary.yaml
      - run:
          name: Deploy to GKE
          command: kubectl apply -f ~/build/services/template/production/deployment-canary.yaml
      - run:
          name: Push the new version to git
          command: |
            cd ~/build
            git config user.email "cicdrunner@template.com"
            git config user.name "CI/CD"
            git add ./services/template/production
            git commit -m "Update image tag to new-tag"
            git push origin main


  deploy-prod:
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker
      - run:
          name: Authenticate with GCP
          command: echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > ${HOME}/gcp-key.json
      - run:
          name: Set up gcloud and kubectl
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
            gcloud config set project testing-234907
            gcloud container clusters get-credentials prod-cluster --region asia-southeast1
      - run:
          name: Fetch and update latest build config
          command: |
            git clone https://workflowr:$GITHUB_PAT@github.com/tkuchh/build.git ~/build
            cd ~/build/services/template/production
            sed -i "s|image:\(.*\)/template:.*|image:\1/template:$CIRCLE_SHA1|" ./deployment.yaml
      - run:
          name: Deploy to GKE
          command: kubectl apply -f ~/build/services/template/production/deployment.yaml
      - run:
          name: Push the new version to git
          command: |
            cd ~/build
            git config user.email "cicdrunner@template.com"
            git config user.name "CI/CD"
            git add ./services/template/production
            git commit -m "Update image tag to new-tag"
            git push origin main

workflows:
  version: 2
  build-test-release:
    jobs:
      - build-and-test:
          context: gcp_credentials
          filters:
            branches:
              only: main
      - deploy-dev:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - build-and-test
          filters:
            branches:
              only: main
      - hold-for-approval:
          type: approval
          requires:
            - deploy-dev
      - deploy-prod-canary:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - hold-for-approval
          filters:
            branches:
              only: main
      - hold-for-canary-confirmation:
          type: approval
          requires:
            - deploy-prod-canary
      - deploy-prod:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - hold-for-canary-confirmation
          filters:
            branches:
              only: main