version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.0

jobs:
  build-and-test:
    executor:
      name: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-and-push-image:
          image: gcr.io/testing-234907/template
          tag: '$CIRCLE_SHA1,latest'
      - run:
          name: Run Tests in Docker Image
          command: |
            docker run --env-file env_vars gcr.io/testing-234907/template:$CIRCLE_SHA1 pytest /code/tests/

  deploy-dev:
    executor:
      name: gcp-gcr/default
    steps:
      - gcp-gcr/gcr-auth
      - run:
          name: Set up gcloud and kubectl
          command: |
            gcloud config set project testing-234907
            gcloud container clusters get-credentials dev-cluster --region asia-southeast1
      - run:
          name: Fetch and update latest build config
          command: |
            git clone https://workflowr:$GITHUB_PAT@github.com/tkuchh/build.git ~/build
            cd ~/build/services/template/development
            sed -i "s|image:\(.*\)/template:.*|image:\1/template:$CIRCLE_SHA1|" ./deployment.yaml
      - run:
          name: Deploy to GKE
          command: kubectl apply -f ~/build/services/template/development/deployment.yaml
      - run:
          name: Push the new version to git
          command: |
            cd ~/build
            git config user.email "cicdrunner@template.com"
            git config user.name "CI/CD"
            git add ./services/template/development
            git commit -m "Update image tag to $CIRCLE_SHA1"
            git push origin main

  deploy-prod-canary:
    executor:
      name: gcp-gcr/default
    steps:
      - run:
          name: Placeholder for running canary deployment.yaml
          command: echo "Hello, world!"

  deploy-prod:
    executor:
      name: gcp-gcr/default
    steps:
      - run:
          name: Placeholder for deploying full production yaml
          command: echo "Hello, world!"

workflows:
  version: 2
  build-test-release:
    jobs:
      - build-and-test:
          context: gcp_credentials
          filters:
            branches:
              only: main
      - deploy-dev:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - build-and-test
          filters:
            branches:
              only: main
      - hold-for-approval:
          type: approval
          requires:
            - deploy-dev
      - deploy-prod-canary:
          context: gcp_credentials
          requires:
            - hold-for-approval
          filters:
            branches:
              only: main
      - hold-for-canary-confirmation:
          type: approval
          requires:
            - deploy-prod-canary
      - deploy-prod:
          context: gcp_credentials
          requires:
            - hold-for-canary-confirmation
          filters:
            branches:
              only: main
