version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.0
  deploy-orb: tkuchh/deploy-orb@0.0.8


jobs:
  build-and-test:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Export Environment Variables
          command: |
            env > env_vars
            echo "CONFIGMAP_VARIABLE=success" >> env_vars
            echo "SECRETS_VARIABLE=success" >> env_vars
      - build:
          dockerfile_path: .
          image_name: template
          test_runner_env_file: ./env_vars
          test_runner_command: pytest /code/tests/

  deploy-dev:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: dev-cluster
      - deploy:
          config_path: services/template/development
          config_file: deployment.yaml
          image_name: template
          namespace: template
          image_tag: $CIRCLE_SHA1
          deployment_name: template

  deploy-prod-canary:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: prod-cluster
      - deploy:
          config_path: services/template/production
          config_file: deployment-canary.yaml
          image_name: template
          image_tag: $CIRCLE_SHA1
          namespace: template
          deployment_name: template-canary

  rollback-prod-canary:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: prod-cluster
      - rollback:
          config_path: services/template/production
          config_file: deployment-canary.yaml
          image_name: template
          namespace: template
          deployment_name: template-canary

  split-traffic-90-10:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          command: echo "Hello, world!"

  split-traffic-70-30:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          command: echo "Hello, world!"

  split-traffic-30-70:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          command: echo "Hello, world!"

  full-deployment:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: prod-cluster
      - deploy:
          config_path: services/template/production
          config_file: deployment.yaml
          image_name: template
          image_tag: $CIRCLE_SHA1
          namespace: template
          deployment_name: template

  rollback-prod:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: prod-cluster
      - rollback:
          config_path: services/template/production
          config_file: deployment.yaml
          image_name: template
          namespace: template
          deployment_name: template
      - rollback:
          config_path: services/template/production
          config_file: deployment-canary.yaml
          image_name: template
          namespace: template
          deployment_name: template-canary

workflows:
  version: 2
  build-test-release:
    jobs:
      - build-and-test:
          context: gcp_credentials
          filters:
            branches:
              only: main
      - deploy-dev:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - build-and-test
          filters:
            branches:
              only: main
      - confirm-deploy-prod-canary:
          type: approval
          requires:
            - deploy-dev

      - deploy-prod-canary:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - confirm-deploy-prod-canary
          filters:
            branches:
              only: main

      - confirm-rollback-prod:
          type: approval
          requires:
            - deploy-prod-canary

      - rollback-prod:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - confirm-rollback-canary
          filters:
            branches:
              only: main

      - confirm-90-10-split:
          type: approval
          requires:
            - deploy-prod-canary

      - split-traffic-90-10:
          requires:
            - confirm-90-10-split

      - confirm-70-30-split:
          type: approval
          requires:
            - split-traffic-90-10

      - split-traffic-70-30:
          requires:
            - confirm-70-30-split

      - confirm-50-50-split:
          type: approval
          requires:
            - split-traffic-70-30

      - split-traffic-50-50:
          requires:
            - confirm-30-70-split

      - confirm-full-deployment:
          type: approval
          requires:
            - split-traffic-30-70

      - full-deployment:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - confirm-full-deployment
          filters:
            branches:
              only: main
