version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.0
  deploy-orb: tkuchh/deploy-orb@0.0.25


jobs:
  build-and-test:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Export Environment Variables
          command: |
            env > env_vars
            echo "CONFIGMAP_VARIABLE=success" >> env_vars
            echo "SECRETS_VARIABLE=success" >> env_vars
            
            echo "DB_CONNECTION_URL=docker-compose-url:3306" >> env_vars
            echo "DB_USER=docker-user" >> env_vars
            echo "DB_PASSWORD=docker-password" >> env_vars
      - deploy-orb/build:
          dockerfile_path: .
          image_name: template
          test_runner_env_file: ./env_vars
          test_runner_command: pytest tests/local --junitxml=/test-results/junit.xml
      - run:
          name: Output test results
          command: |
              docker run -p 80:80 --env-file=env_vars -v /tmp/test-results:/test-results gcr.io/tkuchhal/template:ba47d8a3171b0c2972f1a0df965e90e53c3fa50a pytest tests/local --junitxml=/test-results/junit.xml
              ls /tmp
              echo "-----"
              ls /tmp/test-results
              echo "-----"
              cat /tmp/test-results/junit.xml
      - store_test_results:
          path: /tmp/test-results/junit.xml

  deploy-dev:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: dev-cluster
      - deploy-orb/deploy:
          config_path: services/template/development
          config_file: deployment.yaml
          image_name: template
          namespace: template
          image_tag: $CIRCLE_SHA1
          deployment_name: template


  deploy-prod-canary:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: prod-cluster
      - deploy-orb/deploy:
          config_path: services/template/production
          config_file: deployment-canary.yaml
          image_name: template
          image_tag: $CIRCLE_SHA1
          namespace: template
          deployment_name: template-canary

  split-traffic-90-10:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          command: echo "Hello, world!"

  full-deployment:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: prod-cluster
      - deploy-orb/deploy:
          config_path: services/template/production
          config_file: deployment.yaml
          image_name: template
          image_tag: $CIRCLE_SHA1
          namespace: template
          deployment_name: template

  rollback-prod-canary:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: prod-cluster
      - deploy-orb/rollback:
          config_path: services/template/production
          config_file: deployment-canary.yaml
          image_name: template
          namespace: template
          deployment_name: template-canary

  rollback-prod:
    docker:
      - image: google/cloud-sdk
    steps:
      - deploy-orb/connect_to_kubernetes:
          project_id: tkuchhal
          cluster_name: prod-cluster
      - deploy-orb/rollback:
          config_path: services/template/production
          config_file: deployment.yaml
          image_name: template
          namespace: template
          deployment_name: template

workflows:
  version: 2
  build-test-release:
    jobs:
      - build-and-test:
          context: gcp_credentials
          filters:
            branches:
              only: main
      - deploy-dev:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - build-and-test
          filters:
            branches:
              only: main

      - confirm-deploy-prod-canary:
          type: approval
          requires:
            - deploy-dev

      - deploy-prod-canary:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - confirm-deploy-prod-canary
          filters:
            branches:
              only: main

      - confirm-rollback-prod-canary:
          type: approval
          requires:
            - deploy-prod-canary

      - rollback-prod-canary:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - confirm-rollback-prod-canary
          filters:
            branches:
              only: main

      - confirm-90-10-split:
          type: approval
          requires:
            - deploy-prod-canary

      - split-traffic-90-10:
          requires:
            - confirm-90-10-split

      - confirm-full-deployment:
          type: approval
          requires:
            - split-traffic-90-10

      - full-deployment:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - confirm-full-deployment
          filters:
            branches:
              only: main

      - confirm-rollback-prod:
          type: approval
          requires:
            - split-traffic-90-10

      - rollback-prod:
          context:
            - gcp_credentials
            - build_repo_access
          requires:
            - confirm-rollback-prod
          filters:
            branches:
              only: main
