name: Build, test and deploy to dev

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    uses: tkuchhal/build/.github/workflows/build.yaml@main
    with:
      image_name: template
      image_tag: ${{ github.sha }}
      dockerfile_path: "."
      test_run_command: "pip install -r requirements.txt && pytest tests/local --junitxml=pytest_report.xml"
    secrets: inherit

  deploy-image-dev:
    needs: build
    uses: tkuchhal/build/.github/workflows/deploy.yaml@main
    with:
      namespace: template
      deployment_name: template
      image_name: template
      image_tag: ${{ github.sha }}
      deployment_file_path: "modules/kubernetes-deployment/template/development/deployment.yaml"
      target_cluster: dev-cluster
    secrets: inherit
