name: Deploy image to prod

on:
  workflow_run:
    workflows: [ "Build, test and deploy to dev" ]
    types:
      - completed
  workflow_dispatch:


permissions: write-all

jobs:

  deploy-image-prod:
    uses: tkuchhal/build/.github/workflows/deploy.yaml@main
    with:
      namespace: template
      deployment_name: template
      image_name: template
      image_tag: ${{ github.sha }}
      deployment_file_path: "modules/kubernetes-deployment/template/production/deployment.yaml"
      target_cluster: prod-cluster
    secrets: inherit
