name: Build, test and publish image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]

permissions: write-all

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: asia-southeast1-docker.pkg.dev
  REPOSITORY: tkuchhal/containers
  IMAGE_NAME: template
  GITHUB_BUILD_REPO: tkuchhal/build
  DEPLOYMENT_FILE_PATH_DEV: modules/kubernetes-deployment/template/development/deployment.yaml
  DEPLOYMENT_FILE_PATH_PROD: modules/kubernetes-deployment/template/production/deployment.yaml
  BUILD_REPO_WORKSPACE: ${{ github.workspace }}/build-repo

jobs:
  build:
    uses: tkuchhal/build/.github/workflows/build.yaml@main
    with:
      image_name: template
      dockerfile_path: "."
      test_run_command: "pip install -r requirements.txt && pytest tests/local --junitxml=pytest_report.xml"
    secrets: inherit

  deploy-image-dev:
    needs: build
    uses: tkuchhal/build/.github/workflows/deploy.yaml@main
    with:
      namespace: template
      deployment_name: template
      image_url: ${{ needs.build.outputs.image_url }}
      deployment_file_path: "modules/kubernetes-deployment/template/development/deployment.yaml"
      target_cluster: dev-cluster
    secrets: inherit

  deploy-image-prod:
    needs:
      - deploy-image-dev
      - build
    uses: tkuchhal/build/.github/workflows/deploy.yaml@main
    with:
      namespace: template
      deployment_name: template
      image_url: ${{ needs.build.outputs.image_url }}
      deployment_file_path: "modules/kubernetes-deployment/template/production/deployment.yaml"
      target_cluster: prod-cluster
    secrets: inherit
